default:
  image:
    name: pandoc/latex
    entrypoint: ["/bin/sh"]


stages:
  - build

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "ann-y3-ci"'
  script:
    - ./make.sh

  artifacts:
    paths:
      - ./build
  
