default:
  image: git.vertices.tech:5005/infrastructure/pandoclatex:latest

stages:
  - build
build:  
  stage: build

  before_script:
    - pip install -r requirements.txt
  #   - echo "$CI_REGISTRY_USER" $CI_REGISTRY
  #   - docker info
  #   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdir build
    - ./make.sh

  artifacts:
    paths:
      - ./build
