default:
  image: git.vertices.tech:5005/infrastructure/pandoclatex:latest
  before_script:
    - echo "$CI_REGISTRY_USER" $CI_REGISTRY
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build

build:  
  stage: build

  rules:
    - if: '$CI_COMMIT_BRANCH == "ann-y3-ci"'
  script:
    - ./make.sh

  artifacts:
    paths:
      - ./build
  tags:
    - zhy-runner
